name: "🔒 Security Vulnerability"
description: "Report a security vulnerability (will be handled confidentially)"
title: "[Security]: "
labels: ["security", "triage", "priority:critical"]
assignees: ["jamiescottcraik"]

body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Security Vulnerability Report
        
        **IMPORTANT:** If this is a critical security vulnerability, consider reporting it privately via GitHub's Security Advisory feature instead:
        - Go to Security tab → Report a vulnerability
        
        For less critical security issues, you may use this form.
        
        **Reference:** [llm-threat-controls.md](../brainwav/governance/00-core/llm-threat-controls.md)

  - type: checkboxes
    id: disclosure
    attributes:
      label: "Responsible Disclosure"
      options:
        - label: "I understand this is a public issue and will NOT include sensitive details like exploits, credentials, or PII"
          required: true
        - label: "For critical vulnerabilities, I have considered using GitHub's private Security Advisory feature"
          required: true

  - type: dropdown
    id: severity
    attributes:
      label: "Severity (CVSS-based)"
      options:
        - "Critical (CVSS 9.0-10.0) - Immediate action required"
        - "High (CVSS 7.0-8.9) - Significant risk"
        - "Medium (CVSS 4.0-6.9) - Moderate risk"
        - "Low (CVSS 0.1-3.9) - Minor risk"
        - "Informational - Security improvement suggestion"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: "Vulnerability Category"
      description: "Based on OWASP LLM Top 10 and common vulnerability types"
      options:
        - "LLM01 - Prompt Injection"
        - "LLM02 - Insecure Output Handling"
        - "LLM03 - Training Data Poisoning"
        - "LLM04 - Model Denial of Service"
        - "LLM05 - Supply-Chain Vulnerabilities"
        - "LLM06 - Sensitive Information Disclosure"
        - "LLM07 - Insecure Plugin Design"
        - "LLM08 - Excessive Agency"
        - "LLM09 - Overreliance"
        - "LLM10 - Model Theft"
        - "Secrets/Credentials Exposure"
        - "Dependency Vulnerability"
        - "Configuration Security"
        - "Access Control"
        - "Data Validation"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: affected_area
    attributes:
      label: "Affected Component"
      options:
        - "Governance Core (constitution, charter)"
        - "LLM/Agent Interactions"
        - "MCP Connectors"
        - "CI/CD Pipelines"
        - "Dependencies / Supply Chain"
        - "Configuration Files"
        - "Documentation (sensitive info leak)"
        - "Templates"
        - "Scripts / Tooling"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Vulnerability Description"
      description: "Describe the vulnerability WITHOUT including exploit details"
      placeholder: |
        The [component] is vulnerable to [type of attack] because...
        
        DO NOT include:
        - Working exploits
        - Credentials or secrets
        - Personal/sensitive data
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: "Potential Impact"
      description: "What could an attacker do with this vulnerability?"
      placeholder: |
        An attacker could potentially:
        - Access...
        - Modify...
        - Cause...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: "Steps to Identify (NOT exploit)"
      description: "How can maintainers verify this vulnerability exists?"
      placeholder: |
        1. Review file X
        2. Note the pattern Y
        3. This indicates Z
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: "Suggested Mitigation"
      description: "How do you suggest fixing this?"
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: "References"
      description: "CVE IDs, security advisories, or relevant documentation"
      placeholder: |
        - CVE-XXXX-XXXXX
        - https://nvd.nist.gov/...
        - https://owasp.org/...
    validations:
      required: false

  - type: checkboxes
    id: assistance
    attributes:
      label: "Assistance"
      options:
        - label: "I can help develop a fix for this vulnerability"
        - label: "I can help test the fix"
