name: Governance Guard

on:
  pull_request:
  push:
    branches: [main]

jobs:
  readiness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.19.0
      - uses: actions/setup-node@v4
        with:
          node-version: '24.11.0'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile=false
      - run: pnpm readiness:check

  hash-drift:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.19.0
      - uses: actions/setup-node@v4
        with:
          node-version: '24.11.0'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile=false
      - run: pnpm governance:sync-hashes:check

  governance-scripts:
    runs-on: ubuntu-latest
    needs: [readiness, hash-drift]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.19.0
      - uses: actions/setup-node@v4
        with:
          node-version: '24.11.0'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile=false
      - run: pnpm governance:sync-hashes:check
      - run: pnpm readiness:check
      - run: pnpm ensure:tools
