name: Governance Pack — A11y

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

env:
  GOVERNANCE_PACK: a11y

jobs:
  a11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.19.0
      - uses: actions/setup-node@v4
        with:
          node-version: '24.11.0'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile=false
      - run: pnpm test:a11y
